version: '3'
services:
  nginx:
    build:
      context     : ./nginx
    depends_on:
      - php-fpm
    container_name: laravel-nginx
    hostname      : laravel-nginx
    ports:
      - 8000:80
    volumes:
      - ./opt:/opt:cached

  php-fpm:
    build:
      context     : ./php-fpm
    container_name: laravel-php-fpm
    hostname      : laravel-php-fpm
    volumes:
      - ./opt:/opt:cached

  mysql:
    image                : mysql
    container_name       : laravel-mysql
    hostname             : laravel-mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE     : testdb
      MYSQL_USER         : testuser
      MYSQL_PASSWORD     : password
    ports:
      - '33060:3306'

  test-mysql:
    image                : mysql
    container_name       : laravel-test-mysql
    hostname             : laravel-test-mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE     : testdb
      MYSQL_USER         : testuser
      MYSQL_PASSWORD     : password
    ports:
    - '33061:3306'

  chrome:
    image: robcherry/docker-chromedriver
    environment:
      CHROMEDRIVER_WHITELISTED_IPS: ""
      CHROMEDRIVER_PORT: "9515"
    ports:
      - 9515:9515
    cap_add:
      - "SYS_ADMIN"